; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
monitor_speed = 115200
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps = 
	symlink://C:\NonSyncing\Github repository\PrintAnyFormat
	mathieucarbou/ESPAsyncWebServer @3.6.0
	ayushsharma82/ElegantOTA @ ^3.1.5
	ayushsharma82/WebSerial @ ^2.0.6
	bblanchon/ArduinoJson @ ^7.0.2
    fastled/FastLED@^3.6.0
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.1

build_flags =
; set your debug output (default=Serial)
	-D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_ESP32C3_DEV=1
;    -D DEBUG_ESP_PORT=Serial
; comment the folowing line to enable WiFi debugging
; -D NDEBUG
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D CONFIG_ASYNC_TCP_MAX_ACK_TIME=3000
	-D CONFIG_ASYNC_TCP_PRIORITY=10
	-D CONFIG_ASYNC_TCP_QUEUE_SIZE=128
	-D CONFIG_ASYNC_TCP_RUNNING_CORE=1
	-D CONFIG_ASYNC_TCP_STACK_SIZE=4096
	-D WS_MAX_QUEUED_MESSAGES=64
    -D SPI_FREQUENCY=40000000
    -D CURRENT_TIME=$UNIX_TIME

extra_scripts = 
    pre:auto_firmware_version.py